data:
  train:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.voc2007_dataset
        class: VOC2007Dataset
        VOC2007Dataset:
          compound_coef: 0
          # image_dir: '''dataset/VOC2007/train'''
          # label_dir: '''dataset/VOC2007/train'''
          image_dir: '''dataset/PASCALVOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/JPEGImages/'''
          label_dir: '''dataset/PASCALVOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/'''
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            aeroplane: 0
            bicycle: 1
            bird: 2
            boat: 3
            bottle: 4
            bus: 5
            car: 6
            cat: 7
            chair: 8
            cow: 9
            diningtable: 10
            dog: 11
            horse: 12
            motorbike: 13
            person: 14
            pottedplant: 15
            sheep: 16
            sofa: 17
            train: 18
            tvmonitor: 19
          transforms:
            # - iaa.Add(value=(-10, 10), per_channel=True)
            # - iaa.GaussianBlur(sigma=(0, 1))
            # - iaa.MotionBlur()
            # - iaa.JpegCompression(compression=(0, 10))
            - iaa.Fliplr(p=0.5)
            # - iaa.Flipud(p=0.5)
            # - iaa.Grayscale(alpha=(0.0, 0.1))
            # - iaa.Rot90(k=[0, 1, 2, 3], keep_size=False)
            # - iaa.Affine(rotate=(-5, 5), shear=(-5, 5), fit_output=True)
            # - iaa.Crop(percent=(0, 0.1))
            # - iaa.Pad(percent=(0, 0.1), keep_size=False)
            # - iaa.ChangeColorTemperature()
      batch_size: 32
      shuffle: True
      pin_memory: True
      num_workers: 12
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'
  
  train_eval:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.voc2007_dataset
        class: VOC2007Dataset
        VOC2007Dataset:
          compound_coef: 0
          # image_dir: '''dataset/VOC2007/train'''
          # label_dir: '''dataset/VOC2007/train'''
          image_dir: '''dataset/PASCALVOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/JPEGImages/'''
          label_dir: '''dataset/PASCALVOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/'''
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            aeroplane: 0
            bicycle: 1
            bird: 2
            boat: 3
            bottle: 4
            bus: 5
            car: 6
            cat: 7
            chair: 8
            cow: 9
            diningtable: 10
            dog: 11
            horse: 12
            motorbike: 13
            person: 14
            pottedplant: 15
            sheep: 16
            sofa: 17
            train: 18
            tvmonitor: 19
      batch_size: 32
      shuffle: False
      pin_memory: True
      num_workers: 12
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'
  
  valid:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.voc2007_dataset
        class: VOC2007Dataset
        VOC2007Dataset:
          compound_coef: 0
          # image_dir: '''dataset/VOC2007/valid'''
          # label_dir: '''dataset/VOC2007/valid'''
          image_dir: '''dataset/PASCALVOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007/JPEGImages/'''
          label_dir: '''dataset/PASCALVOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007/Annotations/'''
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            aeroplane: 0
            bicycle: 1
            bird: 2
            boat: 3
            bottle: 4
            bus: 5
            car: 6
            cat: 7
            chair: 8
            cow: 9
            diningtable: 10
            dog: 11
            horse: 12
            motorbike: 13
            person: 14
            pottedplant: 15
            sheep: 16
            sofa: 17
            train: 18
            tvmonitor: 19
      batch_size: 32
      shuffle: False
      pin_memory: True
      num_workers: 12
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

loss:
  module: flame.core.loss.focal_loss
  class: FocalLoss
  FocalLoss:
    alpha: 0.25
    gamma: 2.0
    lamda: 50.0
    device: '''cuda'''

model:
  module: flame.core.model.EfficientDetV1.efficientdet
  class: EfficientDet
  EfficientDet:
    pretrained_weight: '''checkpoint/efficientdet_pretrained_weight/efficientdet-d0.pth'''
    head_only: False
    num_classes: 20
    compound_coef: 0
    backbone_pretrained: False
    scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
    aspect_ratios: ['(1.0, 1.0)', '(1.4, 0.7)', '(0.7, 1.4)']

optim:
  module: torch.optim
  class: SGD
  SGD:
    params: config['model'].parameters()
    lr: 0.08
    momentum: 0.9
    nesterov: True

# optim:
#   module: torch.optim
#   class: AdamW
#   AdamW:
#     params: config['model'].parameters()
#     lr: 0.001

train_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['train_eval']
    device: '''cuda'''

valid_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['valid']
    device: '''cuda'''

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      focal_loss:
        module: flame.handlers.metrics.focal_loss.loss
        class: Loss
        Loss:
          loss_fn:
            module: flame.handlers.metrics.focal_loss.focal_loss
            class: FocalLoss
            FocalLoss:
              alpha: 0.25
              gamma: 2.0
              lamda: 50.0
              device: '''cuda'''
          output_transform: 'lambda x: (x[0], x[1], x[2], x[3])'
    attach_to:
      train_evaluator: '''train'''
      valid_evaluator: '''valid'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''train''' 
      - '''valid'''

history:
  module: flame.handlers.checkpoint
  class: History

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: ''''''
    mode: '''train'''

terminate_on_nan:
  module: flame.handlers.terminate_on_nan
  class: TerminateOnNan

lr_scheduler:
  module: flame.handlers.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    score_name: '''focal_loss'''
    evaluator_name: '''valid_evaluator'''
    mode: '''min'''
    patience: 3
    verbose: True

early_stopping:
  module: flame.handlers.early_stopping
  class: EarlyStopping
  EarlyStopping:
    score_name: '''focal_loss'''
    evaluator_name: '''valid_evaluator'''
    mode: '''min'''
    patience: 30

best_saver:
  module: flame.handlers.checkpoint
  class: BestSaver
  BestSaver:
    dirname: '''checkpoint/VOC2007/efficientdet-d0'''
    score_name: '''focal_loss'''
    mode: '''min'''
    evaluator_name: '''valid_evaluator'''
    n_saved: 1

backup_saver:
  module: flame.handlers.checkpoint
  class: BackupSaver
  BackupSaver:
    modules:
      - '''model'''
      - '''optim'''
      - '''backup_saver'''
      - '''best_saver'''
      - '''history'''
      - '''lr_scheduler'''
      - '''early_stopping'''
    dirname: '''checkpoint/VOC2007/efficientdet-d0'''
    save_interval: 1
    n_saved: 1

engine:
  module: flame.core.engine.trainer
  class: Trainer
  Trainer:
    dataset: config['data']['train']
    device: '''cuda'''
    max_epochs: 10000
    max_norm: 0.1
    norm_type: 2

extralibs:
  torch: torch
  iaa: imgaug.augmenters
